#SPDX-License-Identifier: MIT-0
---
# tasks file for elysiajs-app
- name: Install unzip
  become: true
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: yes

- name: Install Bun via curl
  ansible.builtin.shell: |
    curl https://bun.sh/install | bash

- name: Add Bun Envs to ~/.bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
    create: yes
  with_items:
    - 'export BUN_INSTALL=\"{{ ansible_env.HOME }}/.bun\"'
    - 'export PATH=\"{{ ansible_env.HOME }}/.bun/bin:$PATH\"'

- name: Source ~/.bashrc
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.bashrc
  args:
    executable: /bin/bash

- name: Verify if Bun is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.bun/bin/bun"
  register: bun_binary

- name: Clone ElysiaJs Snippet from Abhishek-M-K
  ansible.builtin.git:
    repo: "https://github.com/Abhishek-M-K/ElysiaJs-Redis.git"
    dest: "/home/ubuntu/ElysiaJs-Redis"
    clone: yes
    update: no
  when: bun_binary.stat.exists

- name: Install application dependencies
  become: true
  # environment:
  #   PATH: "/root/.bun/bin:{{ ansible_env.PATH }}"
  # ansible.builtin.shell: |
  #   cd /home/ubuntu/ElysiaJs-Redis && bun install
  # args:
  #   executable: /bin/bash
  ansible.builtin.shell: |
    /home/ubuntu/.bun/bin/bun install
  args:
    chdir: "/home/ubuntu/ElysiaJs-Redis"
  when: bun_binary.stat.exists

- name: Run the application
  become: true
  async: 60 # Run the command in the background
  poll: 0 # Do not wait for the command to finish
  # environment:
  #   PATH: "/root/.bun/bin:{{ ansible_env.PATH }}"
  # ansible.builtin.shell: |
  #   cd /home/ubuntu/ElysiaJs-Redis && bun dev
  # args:
  #   executable: /bin/bash
  ansible.builtin.shell: |
    /home/ubuntu/.bun/bin/bun dev
  args:
    chdir: "/home/ubuntu/ElysiaJs-Redis"
  when: bun_binary.stat.exists

# - name: Install Bun
#   become: true
#   ansible.builtin.shell: |
#     curl -fsSL https://bun.sh/install | bash
#     echo "export BUN_INSTALL=\"/root/.bun\"" >> /root/.bashrc
#     echo "export PATH=\"/root/.bun/bin:\$PATH\"" >> /root/.bashrc
#     source /root/.bashrc
#   args:
#     executable: /bin/bash
#     creates: "/root/.bun/bin/bun"
#   ignore_errors: true
# ansible.builtin.shell: |
#   curl -fsSL https://bun.sh/install | bash
# args:
#   executable: /bin/bash
#   creates: "/root/.bun/bin/bun"