#SPDX-License-Identifier: MIT-0
---
# tasks file for elysiajs-app
- name: Install Bun 
  ansible.builtin.apt:
    name: bun
    state: present
    update_cache: yes

- name: Clone ElysiaJs Snippet from Abhishek-M-K
  ansible.builtin.git:
    repo: "https://github.com/Abhishek-M-K/ElysiaJs-Redis.git"
    dest: "/home/ubuntu/ElysiaJs-Redis"

- name: Install application dependencies
  shell: bun install
  args:
    chdir: "/home/ubuntu/ElysiaJs-Redis"

- name: Run the application
  shell: bun dev
  args:
    chdir: "/home/ubuntu/ElysiaJs-Redis"
